#
# CodeCoverage.io - Configuration File
#

codecov:
  notify:
    require_ci_to_pass: no

comment:
  layout: header, changes, diff

coverage:
  precision: 1
  ignore:
    - src/pywinauto/unittests/.*
    - examples/.*
  status:
    patch: false
