# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - cmd: git add .
      - cmd: rye sync -f
      - cmd: rye build
      - cmd: rye run pytest --cov-report xml:nosetests.xml --cov-report html:.build/tests/ --cov=pywinauto ./src/pywinauto/unittests/test_actionlogger.py
