# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - cmd: git add .
      - cmd: rye sync -f
      - cmd: rye build
      - cmd: rye run pytest --cov-report xml:cov.xml --cov-report html:cov.html --cov=pywinauto .\src\pywinauto\unittests\test_actionlogger.py
