name: atspi CI

on:
  push:
    branches: [main, develop, atspi]
  pull_request:

jobs:
  Linux:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.11"] # "2.7", "3.7", "3.8", "3.9", "3.10"

    env:
      DISPLAY: ":0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip" # caching pip dependencies

      - name: System Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y --no-install-recommends \
            python-setuptools python3-pyatspi python3-setuptools \
            python-tk tk-dev \
            xsel libjavascriptcoregtk-4.0-18 \
            build-essential libssl-dev \
            qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools \
            libxkbcommon-x11-0 \
            python3-gi gobject-introspection gir1.2-gtk-3.0 \
            at-spi2-core \
            gdm3 \
            xvfb x11-utils libxkbcommon-x11-0 \
            libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 \
            libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 xdotool

      - name: Python Packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Generate Test Apps
        run: |
          cd apps
          cd MouseTester/source
          qmake
          make
          chmod a+x mousebuttons
          cp mousebuttons ../
          cd ../..
          cd SendKeysTester/source
          qmake
          make
          chmod a+x send_keys_test_app
          cp send_keys_test_app ../
          echo "XDG_RUNTIME_DIR=/tmp/runtime-runner" >> $GITHUB_ENV

      - name: Start Remote Display
        run: |
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
          sleep 5
          set +eE
          sudo service gdm start
          sleep 5

      - name: Run Tests
        run: |
          coverage run -a --include=pywinauto/mouse.py pywinauto/unittests/test_mouse.py
          coverage run -a --include=pywinauto/linux/keyboard.py pywinauto/unittests/test_keyboard.py
          coverage run -a --include=pywinauto/linux/clipboard.py pywinauto/unittests/test_clipboard_linux.py
          coverage run -a --include=pywinauto/linux/application.py pywinauto/unittests/test_application_linux.py
          coverage run -a --source=pywinauto/linux,pywinauto/controls pywinauto/unittests/test_atspi_element_info.py
          coverage run -a --source=pywinauto/linux,pywinauto/controls pywinauto/unittests/test_atspi_wrapper.py
          coverage run -a --source=pywinauto/linux,pywinauto/controls pywinauto/unittests/test_atspi_controls.py

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
