name: atspi CI

on:
  push:
    branches: [main, develop, atspi]
  pull_request:

jobs:
  Linux:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.11"]  # "2.7", "3.7", "3.8", "3.9", "3.10"

    env:
      DISPLAY: ":0"

    steps:
      - name: get repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt update -y
          sudo apt upgrade
          sudo apt install -y --no-install-recommends python-setuptools tk-dev python-tk
          sudo apt install -y --no-install-recommends python3 python3-pip python3-setuptools
          sudo apt install -y --no-install-recommends python-xlib
          sudo apt install -y --no-install-recommends xsel
          sudo apt install -y libjavascriptcoregtk-4.0-18
          pip install coverage codecov
          pip install python-xlib --upgrade
          pip install mock --upgrade
          python -m pip install pytest
          sudo apt install -y build-essential libssl-dev
          sudo apt install -y qt5-default
          sudo apt install -y libxkbcommon-x11-0
          sudo apt install -y python3-gi gobject-introspection gir1.2-gtk-3.0
          sudo apt install -y at-spi2-core
          sudo apt install -y python3-pyatspi
          sudo apt install -y xvfb x11-utils libxkbcommon-x11-0 \
              libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 \
              libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 xdotool
          #pip3 install scikit-build # required for cmake>=3.23.0
          pip3 install cmake==3.22.6

      - name: Install test apps
        run: |
          cd apps
          cd MouseTester/source
          qmake
          make
          chmod a+x mousebuttons
          cp mousebuttons ../
          cd ../..
          cd SendKeysTester/source
          qmake
          make
          chmod a+x send_keys_test_app
          cp send_keys_test_app ../
          echo "XDG_RUNTIME_DIR=/tmp/runtime-runner" >> $GITHUB_ENV

      - name: Remote display start
        run: |
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
          sleep 5
          set +eE
          sudo apt install -y gdm3
          sudo service gdm start
          sleep 5

      - name: Run tests
        run: >-
          coverage run -m pytest
            pywinauto/unittests/test_atspi_element_info.py
            pywinauto/unittests/test_atspi_wrapper.py
            pywinauto/unittests/test_atspi_controls.py
            pywinauto/unittests/test_clipboard_linux.py
            pywinauto/unittests/test_keyboard.py pywinauto/unittests/test_application_linux.py

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
