name: atspi CI

on:
  push:
    branches: [main, develop, atspi]
  pull_request:

jobs:
  Linux:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.11"]  # "2.7", "3.7", "3.8", "3.9", "3.10"

    env:
      DISPLAY: ":0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt update -y
          sudo apt install -y --no-install-recommends \
            python-setuptools tk-dev python-tk \
            python3 python3-pip python3-setuptools
          sudo apt install -y --no-install-recommends \
            xsel libjavascriptcoregtk-4.0-18
          python -m pip install coverage codecov pytest
          python -m pip install mock python-xlib --upgrade
          sudo apt install -y --no-install-recommends build-essential libssl-dev
          sudo apt install -y --no-install-recommends qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
          sudo apt install -y --no-install-recommends libxkbcommon-x11-0
          sudo apt install -y --no-install-recommends python3-gi gobject-introspection gir1.2-gtk-3.0
          sudo apt install -y --no-install-recommends at-spi2-core
          sudo apt install -y --no-install-recommends python3-pyatspi
          sudo apt install -y --no-install-recommends xvfb x11-utils libxkbcommon-x11-0 \
              libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 \
              libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 xdotool
          python -m pip install scikit-build # required for cmake>=3.23.0
          python -m pip install cmake==3.22.6

      - name: Generate Test Apps
        run: |
          cd apps
          cd MouseTester/source
          qmake
          make
          chmod a+x mousebuttons
          cp mousebuttons ../
          cd ../..
          cd SendKeysTester/source
          qmake
          make
          chmod a+x send_keys_test_app
          cp send_keys_test_app ../
          echo "XDG_RUNTIME_DIR=/tmp/runtime-runner" >> $GITHUB_ENV

      - name: Start Remote Display
        run: |
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
          sleep 5
          set +eE
          sudo apt install -y gdm3
          sudo service gdm start
          sleep 5

      - name: Run Tests
        run: >-
          coverage run -m pytest
            pywinauto/unittests/test_atspi_element_info.py
            pywinauto/unittests/test_atspi_wrapper.py
            pywinauto/unittests/test_atspi_controls.py
            pywinauto/unittests/test_clipboard_linux.py
            pywinauto/unittests/test_keyboard.py pywinauto/unittests/test_application_linux.py

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
